### ISSUE TITLE
Замечания по работе

### ISSUE THREAD

**Issue by AndriiLitvin** [Speariv35/speariv35.github.io#1]
Ставлю ЗАЧЕТ надеюсь исправишь)
По коду: 
1) поставь border-radius фотографии и блоку с контентом(визитка)
А так в общем ничего смертельного нет, но есть некоторые советы как делать в следующий раз) если делаешь бордер через hr то лучше делать один класс так как они одинаковые, а все отступы делать от блоков с текстом. название классов  нужно выбирать говорящие, чтоб не зная что там находится программист  по классу мог понять что за данные там должны быть. отступы делать через &#60;br&#62; не кайфово. пользуйся margin или padding, если нужно перенести блок на следующую страницу как тут "&#60;p class="block"&#62;Мой профиль вконтакте &#60;br&#62;&#60;a href="https://www.facebook.com/kostiantyn.kostenko" &#62; vk.com &#60;/a&#62; &#60;/p&#62;"  вместо &#60;br&#62; делай через CSS 
допустим так ".block>a {display:block;}"

**Comment by Speariv35** [comment]
Добавил border-radius для картинки и блоку с контентом.

Спасибо за советы насчет hr и переноса строк.  
Я под конец верстки, уже сам начал понимать что начудил с hr. И тут конечно сыграло свою роль то, что пока сложно составить детальный план, до того как начну верстать, и он формируется только по ходу верстки. Но это все недостаток опыта верстки.

**Comment by AndriiLitvin** [comment]
Первое задание ЗАЧЕТ!

**Comment by AndriiLitvin** [comment]
Да все придет, все будет)

**Comment by AndriiLitvin** [comment]
А css то я твой особо не смотрел font-size в %??? делай через 'px' и как ты вообще по макету высчитал что там такой процент? Так не делай) Поменяй пожалуйста на 'px' или "em". Просто в % задавать в отдельных случаях, ну тут по идеи это не уместно.

**Comment by Speariv35** [comment]
Ок.  :)

**Comment by AndriiLitvin** [comment]
Вместо < hr > сделай блоку border-bottom

**Comment by Speariv35** [comment]
Да я после вчерашнего вебинара уже переделал)  Скоро запушу на ГитХаб.

**Comment by Speariv35** [comment]
Сделал рефакторинг по новым веяниям моды :)
