### ISSUE TITLE
Замечание экзамен js

### ISSUE THREAD

**Issue by AndriiLitvin** [Speariv35/speariv35.github.io#20]
1
![image](https://cloud.githubusercontent.com/assets/13675947/13981441/d1e74ba4-f0ec-11e5-8c11-b2ff4b820ada.png)
тут ссылки не нужны.
2
![image](https://cloud.githubusercontent.com/assets/13675947/13981517/312473ee-f0ed-11e5-83e4-09baca1a74fa.png)
здесь можно сделать через after before

а так то вроде норм. ну твою работу на вебинаре смотрели))

поправь это))

**Comment by Speariv35** [comment]
Ок поправлю ... Не смотрел вебинар не знаю .... Но если это тот что был  15 числа, то я тогда еще ничего  не сделал. Я его в воскресенье за день склепал. Опять времени не было.  Там на вебинаре вроди как CasTroy (Жени) смотрели работу.

**Comment by AndriiLitvin** [comment]
Сорри знач попутал) ну знач норм

**Comment by Speariv35** [comment]
Ссылки убрал и сделал через :before

**Comment by AndriiLitvin** [comment]
![image](https://cloud.githubusercontent.com/assets/13675947/14019201/40ffff52-f1da-11e5-923b-e2e03967108c.png)
в ие8 что то с шрифтами

![image](https://cloud.githubusercontent.com/assets/13675947/14019233/64d5423e-f1da-11e5-830b-da1d3c058049.png)

и на ие плитка не работает

**Comment by Speariv35** [comment]
Подлечил шрифты в ИЕ 8.  И плитка работает точно - проверял. Возможно с утра не работал сервис API которого мы берем.

**Comment by AndriiLitvin** [comment]
1 Подправь
![image](https://cloud.githubusercontent.com/assets/13675947/14042035/d93dd2fe-f27e-11e5-85cf-bc49394d82b7.png)

2 тут на картинках на макете полупрозрачный темный фон есть. Сделай его и чтоб по ховеру он пропадал и по клику на картинку она была на всю свою ширину в попапе.
![image](https://cloud.githubusercontent.com/assets/13675947/14042198/630ef516-f280-11e5-977b-3d7858df0889.png)

**Comment by Speariv35** [comment]
http://speariv35.github.io/GoIT/javascript/exam1/build/    да у меня уже такая версия есть .  

с фансибоксом.  на слайдере прикручу градиент.

**Comment by AndriiLitvin** [comment]
ок. поправь шрифт на этой версии и чтоб картинки в плитке первый раз рамдомные высвечивались. и зачет

**Comment by Speariv35** [comment]
Поправил шрифты.... вечно забываю для подстраховки стандартные дописывать.

**Comment by Speariv35** [comment]
Все что просил поправил. Что то еще нужно доделать или все ок?

**Comment by AndriiLitvin** [comment]
1.  у тебя теперь нормально не работает плитка ну поиск картинок (' Uncaught TypeError: Cannot read property 'webformatURL' of undefined     main.js:172')
   ![image](https://cloud.githubusercontent.com/assets/13675947/14139456/e05ac690-f67b-11e5-9bf7-5b831a02abb8.png)
2.  убери фокус и outline
3.  и ты не совсем правильно понял на счет плитки. там при каждой загрузки странички высвечиваются картинки с одинаковым названием , но когда перезагружаешь то название меняется и картинки тоже.
4. в ИЕ такие ошибки 
   ![image](https://cloud.githubusercontent.com/assets/13675947/14139675/254723b0-f67d-11e5-8509-1b8ca63f21bb.png)

**Comment by AndriiLitvin** [comment]
я подумал и короч ЗАЧЕТ
