### ISSUE TITLE
Замечания по работе 5.1 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [Speariv35/speariv35.github.io#4]
1) при увеличении ширины экрана менюшка улетает вправо
2) кнопку попробуй сделать через тег < a > и используя :after :before
3)бордер под заголовком "Cadastre-se" толще

**Comment by Speariv35** [comment]
1) Ну по шаблону оно и не должно быть отцентрировано. Так что мне его центрировать? 
2) Сделал через тег а. Добавил Букву F черз before.
3) Бордер - имеется ввиду прозрачная линия между Кадастре и формой? Перфект пиксель показывает что она один в один. Ее высота 2 пикселя - у меня тоже 2 пикселя.

**Comment by AndriiLitvin** [comment]
> 1) Ну по шаблону оно и не должно быть отцентрировано. Так что мне его центрировать? 

центрировать не нужно,  пихаешь просто контент хедера у контейнер и задаешь ширину и выравниваешь по центру. а хедер ровняешь по правому краю.
< div class="content__button">< a class="link" href="#"> - такая конструкция в общем не нужна, можно выбросить див и просто добавить тегу "а" класс дива.

http://joxi.ru/Q2K7zPpsza832j
1. тут сделай как я писал выше
2. сверстать а не картинкой
3. < div class="space">&nbsp;< /div> - так никто не делает и это не кайфово. сделай отступ блоку
4. зачем оборачивать все в wrapper если там нет свойств

**Comment by Speariv35** [comment]
1. Сделал хеадер враппер 1215.
2. Сверстал
3. Переделал. Правда я изначально так делал но появилась проблема в Фаерфоксе. Нашел временное решение а потом забыл убрать.
4. Убрал враппер

**Comment by AndriiLitvin** [comment]
хех ну почти вот еще
http://joxi.ru/KAgGg68tRDwXAl
1) цвет текста
2)вертикально текст от центрируй

**Comment by Speariv35** [comment]
1) Цвет поменял
2) Ну по перфект пикселю, опять же все по макету :)

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
