### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [Speariv35/speariv35.github.io#7]
## 1. экран 960 http://joxi.ru/4AkegKpfMNEMVm

1)text-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
2)заменить на разные иконки
3)text-shadow: 0px 1px 0px #0f1518;
4)нет треугольника 
5)6) там показывается активный слайд
7)под логотипами компаний (6 шт) там просто бордер
8)ширина меньше
9)text-shadow: 0px 1px 0px #ffffff;
10) поменяй блок. чтоб он появлялся только при большом  экране. либо замени на всех чтоб одинаковый везде контент был.
11)отступ меньше.
## 2. экран 768 http://joxi.ru/GrqgjnLtNndbY2

1)2)ширина как заголовок
3)ширина меньше
4) там норм просто не досмотрел что там слова не хватает
5)вертикально отцентрировать
6)ширина меньше
## 3. экран 480 http://joxi.ru/KAgGg68tgnb6DA

1)убрать отступ
2)3)5) меньше ширина
4)перенести картинку
6)отцентрировать
## 4. экран 320 http://joxi.ru/Vm67Z8QsxVdQy2

1) подровняй

вообщем сделай чтоб на этих экранах максимальная точность с макетом была

**Comment by AndriiLitvin** [comment]
у тебя не совсем правильно медиа квери прописаны. сначала идут большие экраны а потом меньше и меньше. + судя по вчерашниму вебинару то там такие экраны
320-479 480-767 768-959 и 960

**Comment by Speariv35** [comment]
Тогда я не понимаю технологии mobile first.

**Comment by Speariv35** [comment]
и еще одна проблема что в ДЗ нет ТЗ :) и все как поняли так и делают.

**Comment by Speariv35** [comment]
1. экран 320
2. экран 480  http://joxi.ru/L21zqjQse7JkAX
   1)Убрал отступ
   2)3)5) меньше ширина   -   по перфекту все ок.  Скрин  сверху. Может ты на большей ширине смотрел
   4)перенести картинку - опять же у меня на 480 все ок. А  потом при расширение они перепрыгивают. Как  по мне это нормально.
   6)Отцентрировал
3. экран 768 
   1)2)ширина как заголовок   - Оно так и есть на 768px потом они растягиваются с шириной.
   3)ширина меньше  - тоже самое на 768px все по макету потом он растягивается и опять же я считаю это правильно.
   4) там норм просто не досмотрел что там слова не хватает  - у меня есть) может позже добавил )
   5)вертикально отцентрировать - отцентрировал
   6)ширина меньше - опять же 768 все ок  потом растягивается.
4. экран 960 

1)text-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);  - поменял
2)заменить на разные иконки   - сделал
3)text-shadow: 0px 1px 0px #0f1518;  -    поменял
4)нет треугольника    - сделал
5)6) там показывается активный слайд - сделал
7)под логотипами компаний (6 шт) там просто бордер  -   сделал
8)ширина меньше - сделал
9)text-shadow: 0px 1px 0px #ffffff; -  поменял
10) поменяй блок. чтоб он появлялся только при большом экране. либо замени на всех чтоб одинаковый везде контент был.   - сделал.
11)отступ меньше.  - сделал

**Comment by AndriiLitvin** [comment]
1) тут горизонтальный скрол появился http://joxi.ru/vAWZzP3skjMwv2

## Экран 960 http://joxi.ru/J2blgP1F4xzOGr

1)text-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
2)4) text-shadow: 0px 1px 0px #ffffff;
3) вертикально отцентрируй

## Экран 768 http://joxi.ru/Y2L0zPXsnwaWQ2

1)блок с текстом уже, на ширину подзаголовка
2)на мозиле бывает смещается
3)ширина такая же как заголовок
4) ширина меньше

## Экран 480 http://joxi.ru/MAjlEL1FvRpl3m

1)меню шире
2)подними чутка айфон верх
3)тут падинги не те ну вот такие по макету padding: 30px 32px 35px 38px;
4)на всем блоке text-shadow: 0px 1px 0px #ffffff;
5)картинку перенести
6)уже блок
7)по макету ширина мобильного враппера выходит 435px. 

## Экран 320 http://joxi.ru/l2Z64PNu8DqJb2

1)ширина меньше
2)тут padding:35px 40px 33px 38px;
3)переместить чтоб вровень с текстом было
4)отцентрировать
тут враппер разный на всех блоках где 260 где 272

**Comment by AndriiLitvin** [comment]
## Экран 480 http://joxi.ru/GrqgjnLtNNx1a2 

1) все норм но тут.... тут не нужно делать через спрайты. просто картинкой. так как это логотипы компаний и они могут меняться. и там поидеи через ссылки не нужно.

## Экран 320 http://joxi.ru/Y2L0zPXsnn8nj2

отцентрируй их. 

пересмотри свой код по поводу БЭМ https://ru.bem.info/method/solved-problems/

**Comment by Speariv35** [comment]
1) сделал через картинки  Подровнял все.
2) Отцентрировал http://joxi.ru/823xMj6SE79OAO
3) Я пользовался этим руководством http://frontender.info/MindBEMding/   Ему вроди как соответствует.

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
